# Generated by Django 2.2.28 on 2025-05-01 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200724_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='job_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.JobCategory'),
        ),
        migrations.AlterField(
            model_name='eventjobcategorylinking',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_category_links', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='eventjobcategorylinking',
            name='job_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_links', to='events.JobCategory'),
        ),
    ]
